name: PKGBUILD CI
on: 
  push:
  workflow_dispatch:
jobs:
  build_with_gcc_x86_64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0
    - name: Makepkg Build and Check
      id: makepkg
      uses: edlanglois/pkgbuild-action@v1.1.8
      with:
          pkgdir: "gcc-x86-64-actiondir"
          namcapDisable: 1
          makepkgArgs: "--skippgpcheck --noconfirm -s"
    - name: Release
      uses: ncipollo/release-action@v1.11.1
      with:
          allowUpdates: true
          tag: "6.0.8-1-gcc-x86-64"
          commit: master
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
  build_with_llvm_lto_x86_64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0
    - name: Makepkg Build and Check
      id: makepkg
      uses: edlanglois/pkgbuild-action@v1.1.8
      with:
          pkgdir: "llvm-lto-x86-64-actiondir"
          namcapDisable: 1
          makepkgArgs: "--skippgpcheck --noconfirm -s"
    - name: Release
      uses: ncipollo/release-action@v1.11.1
      with:
          allowUpdates: true
          tag: "6.0.8-1-llvm-lto-x86-64"
          commit: master
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
  build_with_gcc_x86_64_v3:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0
    - name: Makepkg Build and Check
      id: makepkg
      uses: edlanglois/pkgbuild-action@v1.1.8
      with:
          pkgdir: "gcc-x86-64-v3-actiondir"
          namcapDisable: 1
          makepkgArgs: "--skippgpcheck --noconfirm -s"
    - name: Release
      uses: ncipollo/release-action@v1.11.1
      with:
          allowUpdates: true
          tag: "6.0.8-1-gcc-x86-64-v3"
          commit: master
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
  build_with_llvm_lto_x86_64_v3:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0
    - name: Makepkg Build and Check
      id: makepkg
      uses: edlanglois/pkgbuild-action@v1.1.8
      with:
          pkgdir: "llvm-lto-x86-64-v3-actiondir"
          namcapDisable: 1
          makepkgArgs: "--skippgpcheck --noconfirm -s"
    - name: Release
      uses: ncipollo/release-action@v1.11.1
      with:
          allowUpdates: true
          tag: "6.0.8-1-llvm-lto-x86-64-v3"
          commit: master
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
